### PR TITLE
Fixing build issue on newer linux and also issues with newer Ruby

### LINKED ISSUE #15: No longer builds on latest ARCH linux
Installing/building the native extension is no longer possible on latest Arch-Linux.

Kernel 6.10.9
GCC 14.2.1

The compilation fails with following error (only presenting the last lines of the output):

```
sigar_util.c:652:19: warning: initialization discards ‘const’ qualifier from pointer target type [-Wdiscarded-qualifiers]
  652 |     CPU_MODEL_ENT("Duron"),
      |                   ^~~~~~~
sigar_util.c:627:7: note: in definition of macro ‘CPU_MODEL_ENT_R’
  627 |     { s, sizeof(s)-1, r, sizeof(r) }
      |       ^
sigar_util.c:652:5: note: in expansion of macro ‘CPU_MODEL_ENT’
  652 |     CPU_MODEL_ENT("Duron"),
      |     ^~~~~~~~~~~~~
sigar_util.c:652:19: warning: initialization discards ‘const’ qualifier from pointer target type [-Wdiscarded-qualifiers]
  652 |     CPU_MODEL_ENT("Duron"),
      |                   ^~~~~~~
sigar_util.c:627:23: note: in definition of macro ‘CPU_MODEL_ENT_R’
  627 |     { s, sizeof(s)-1, r, sizeof(r) }
      |                       ^
sigar_util.c:652:5: note: in expansion of macro ‘CPU_MODEL_ENT’
  652 |     CPU_MODEL_ENT("Duron"),
      |     ^~~~~~~~~~~~~
sigar_util.c:653:21: warning: initialization discards ‘const’ qualifier from pointer target type [-Wdiscarded-qualifiers]
  653 |     CPU_MODEL_ENT_R("K6(tm)-III", "K6 III"),
      |                     ^~~~~~~~~~~~
sigar_util.c:627:7: note: in definition of macro ‘CPU_MODEL_ENT_R’
  627 |     { s, sizeof(s)-1, r, sizeof(r) }
      |       ^
sigar_util.c:653:35: warning: initialization discards ‘const’ qualifier from pointer target type [-Wdiscarded-qualifiers]
  653 |     CPU_MODEL_ENT_R("K6(tm)-III", "K6 III"),
      |                                   ^~~~~~~~
sigar_util.c:627:23: note: in definition of macro ‘CPU_MODEL_ENT_R’
  627 |     { s, sizeof(s)-1, r, sizeof(r) }
      |                       ^
sigar_util.c:654:21: warning: initialization discards ‘const’ qualifier from pointer target type [-Wdiscarded-qualifiers]
  654 |     CPU_MODEL_ENT_R("K6(tm) 3D+", "K6 3D+"),
      |                     ^~~~~~~~~~~~
sigar_util.c:627:7: note: in definition of macro ‘CPU_MODEL_ENT_R’
  627 |     { s, sizeof(s)-1, r, sizeof(r) }
      |       ^
sigar_util.c:654:35: warning: initialization discards ‘const’ qualifier from pointer target type [-Wdiscarded-qualifiers]
  654 |     CPU_MODEL_ENT_R("K6(tm) 3D+", "K6 3D+"),
      |                                   ^~~~~~~~
sigar_util.c:627:23: note: in definition of macro ‘CPU_MODEL_ENT_R’
  627 |     { s, sizeof(s)-1, r, sizeof(r) }
      |                       ^
sigar_util.c: In function ‘sigar_log_printf’:
sigar_util.c:919:5: warning: function ‘sigar_log_printf’ might be a candidate for ‘gnu_printf’ format attribute [-Wsuggest-attribute=format]
  919 |     vsnprintf(buffer, sizeof(buffer), format, args);
      |     ^~~~~~~~~
sigar_util.c: In function ‘sigar_time_now_millis’:
sigar_util.c:980:5: error: implicit declaration of function ‘gettimeofday’ [-Wimplicit-function-declaration]
  980 |     gettimeofday(&tv, NULL);
      |     ^~~~~~~~~~~~
At top level:
cc1: note: unrecognized command-line option ‘-Wno-self-assign’ may have been intended to silence earlier diagnostics
cc1: note: unrecognized command-line option ‘-Wno-parentheses-equality’ may have been intended to silence earlier diagnostics
cc1: note: unrecognized command-line option ‘-Wno-constant-logical-operand’ may have been intended to silence earlier diagnostics
make: *** [Makefile:248: sigar_util.o] Error 1

make failed, exit code 2

```

### PR DESCRIPTION
**Pull request by wollistik**
Added now mandatory include and updated Rakefile to be compatible with newer Ruby versions.
Fixes #15

### CODE REVIEW

**Comment by kostya** [comment]
thanks, but would it work on older ruby versions? maybe add check if no `File.exists?` method, define it as alias?

**Comment by kostya** [comment]
also this line `#include <sys/time.h>` 
may be need to add only into file `linux_sigar.c`, because I don't know how it would work on other systems.

**Comment by wollistik** [comment]
`File.exists?`  was deprecated since Ruby 2.1 and was merely an alias to `File.exist?`. `File.exist?` has been in Ruby since 1.8.6, so I don't see any serious compatibility issues. With Ruby 3.2 the `exists?` method now has finally been removed.

**Comment by wollistik** [comment]
> also this line `#include <sys/time.h>` may be need to add only into file `linux_sigar.c`, because I don't know how it would work on other systems.

I will check this and update the PR when it works.

**Comment by wollistik** [comment]
> > also this line `#include <sys/time.h>` may be need to add only into file `linux_sigar.c`, because I don't know how it would work on other systems.
> 
> I will check this and update the PR when it works.

Tried to move the include only in `linux_sigar.c`, but this did not work. It has to added in `sigar_util.c`

But if you look closer in the PR, the include is only done when not on Windows (see line 29 of `sigar_util.c`). Also the only function where `gettimeofday` from `sys/time.h` is called is in `sigar_time_now_millis`, which is also wrapped in a `#ifndef WIN32` block (see lines 977 - 984).

**Comment by kostya** [comment]
thanks, push gem 2.0.11

**Pull request merged**
